steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "_DATABASE_URL=$(gcloud secrets versions access latest --secret=DATABASE_URL | tr -d '\n')" >> $HOME/substitutions
    echo "_DATABASE_USERNAME=$(gcloud secrets versions access latest --secret=DATABASE_USERNAME | tr -d '\n')" >> $HOME/substitutions
    echo "_DATABASE_PASSWORD=$(gcloud secrets versions access latest --secret=DATABASE_PASSWORD | tr -d '\n')" >> $HOME/substitutions
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "Backend/app.yml"]
  env: ['envsubst < $HOME/substitutions']
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DATABASE_URL: "DATABASE_URL_PLACEHOLDER"
  _DATABASE_USERNAME: "DATABASE_USERNAME_PLACEHOLDER"
  _DATABASE_PASSWORD: "DATABASE_PASSWORD_PLACEHOLDER"