runtime: java17
instance_class: F2
entrypoint: 'java -jar ./build/libs/back-0.0.1-SNAPSHOT.jar'
env_variables:
  DATABASE_URL: "jdbc:postgresql://events-system.c7eeu2g6ctsw.us-east-1.rds.amazonaws.com:5432/postgres"
  DATABASE_USERNAME: "Bieber_Fever"
  DATABASE_PASSWORD: "Bieber-Fever1234"