runtime: java17
instance_class: F2
entrypoint: 'java -jar ./build/libs/back-0.0.1-SNAPSHOT.jar'
env_variables:
  DATABASE_URL: "${_DATABASE_URL}"
  DATABASE_USERNAME: "${_DATABASE_USERNAME}"
  DATABASE_PASSWORD: "${_DATABASE_PASSWORD}"