name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
      - develop
      - feat/backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: `google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        export_default_credentials: true

        
    - name: Deploy to App Engine
      run: |
        cd Backend
        gcloud app deploy app.yml
